import { StyleSheet } from 'react-native';
export const ArithStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f0f9ff',
    },
    resultCard: {
        alignItems: 'center',
        paddingVertical: 26,
        marginTop: 12,
        marginBottom: 24,
        backgroundColor: '#0ea5e9',
        borderRadius: 22,
        shadowColor: '#0ea5e9',
        shadowOpacity: 0.35,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
    },
    resultCardNegative: {
        backgroundColor: '#ef4444',
        shadowColor: '#ef4444',
    },
    resultLabel: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 3,
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 4,
    },
    resultValue: {
        fontSize: 40,
        fontWeight: '800',
        color: '#ffffff',
    },
    inputGroup: {
        marginBottom: 14,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.5,
        color: '#7ca6c0',
        marginBottom: 6,
        marginLeft: 4,
    },
    TextInput: {
        borderWidth: 1,
        borderColor: '#bae6fd',
        borderRadius: 16,
        backgroundColor: '#ffffff',
        paddingVertical: 15,
        paddingHorizontal: 18,
        fontSize: 18,
        color: '#0c4a6e',
        shadowColor: '#0c4a6e',
        shadowOpacity: 0.04,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
    },
    addButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: '#0ea5e9',
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#0ea5e9',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    subButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: '#06b6d4',
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#06b6d4',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    resetButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: '#0c4a6e',
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#0c4a6e',
        shadowOpacity: 0.25,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    buttonText: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#ffffff',
        letterSpacing: 0.5,
    },
    button_pack: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 8,
    }
});
