import { StyleSheet } from 'react-native';
export const ArithStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 10,
        backgroundColor: '#f2f6fc',
    },
    TextInput: {
        borderWidth: 1,
        borderColor: '#c5d3e8',
        borderRadius: 10,
        backgroundColor: '#ffffff',
        padding: 14,
        fontSize: 16,
        marginHorizontal: 10,
        marginVertical: 6,
    },
    TextResult: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
        alignSelf: 'stretch',
        marginHorizontal: 10,
        marginTop: 40,
        marginBottom: 20,
        paddingVertical: 20,
        backgroundColor: '#1e3a5f',
        borderRadius: 12,
        shadowColor: '#1e3a5f',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    addButton: {
        backgroundColor: '#86efac',
        paddingVertical: 14,
        paddingHorizontal: 24,
        margin: 6,
        borderRadius: 10,
        minWidth: 90,
        alignItems: 'center',
        elevation: 2,
    },
    subButton: {
        backgroundColor: '#fcd34d',
        paddingVertical: 14,
        paddingHorizontal: 24,
        margin: 6,
        borderRadius: 10,
        minWidth: 90,
        alignItems: 'center',
        elevation: 2,
    },
    resetButton: {
        backgroundColor: '#fca5a5',
        paddingVertical: 14,
        paddingHorizontal: 24,
        margin: 6,
        borderRadius: 10,
        minWidth: 90,
        alignItems: 'center',
        elevation: 2,
    },
    button_pack: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
    }
});
