import { StyleSheet } from 'react-native';
import { Colors } from './colors';
export const ArithStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: Colors.background,
    },
    resultCard: {
        alignItems: 'center',
        paddingVertical: 26,
        marginTop: 12,
        marginBottom: 24,
        backgroundColor: Colors.primary,
        borderRadius: 22,
        shadowColor: Colors.primary,
        shadowOpacity: 0.35,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
    },
    resultCardNegative: {
        backgroundColor: Colors.danger,
        shadowColor: Colors.danger,
    },
    resultLabel: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 3,
        color: Colors.whiteFaded,
        marginBottom: 4,
    },
    resultValue: {
        fontSize: 40,
        fontWeight: '800',
        color: Colors.white,
    },
    inputGroup: {
        marginBottom: 14,
    },
    inputLabel: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.5,
        color: Colors.muted,
        marginBottom: 6,
        marginLeft: 4,
    },
    TextInput: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 16,
        backgroundColor: Colors.white,
        paddingVertical: 15,
        paddingHorizontal: 18,
        fontSize: 18,
        color: Colors.dark,
        shadowColor: Colors.dark,
        shadowOpacity: 0.04,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
    },
    addButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: Colors.primary,
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.primary,
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    subButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: Colors.secondary,
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.secondary,
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    mulButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: Colors.teal,
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.teal,
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    divButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: Colors.deepBlue,
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.deepBlue,
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    resetButton: {
        flex: 1,
        flexDirection: 'row',
        gap: 4,
        backgroundColor: Colors.dark,
        paddingVertical: 15,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.dark,
        shadowOpacity: 0.25,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    buttonText: {
        fontSize: 15,
        fontWeight: 'bold',
        color: Colors.white,
        letterSpacing: 0.5,
    },
    button_pack: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 8,
    }
});
