import { StyleSheet } from "react-native";
import { Colors } from './colors';

export const CountStyle = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.background,
    },
    card: {
        alignSelf: 'stretch',
        alignItems: 'center',
        paddingVertical: 44,
        marginBottom: 36,
        backgroundColor: Colors.white,
        borderRadius: 28,
        shadowColor: Colors.primary,
        shadowOpacity: 0.15,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    cardLabel: {
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 3,
        color: Colors.muted,
        marginBottom: 6,
    },
    cardValue: {
        fontSize: 72,
        fontWeight: '800',
        color: Colors.dark,
    },
    cardValueNegative: {
        color: Colors.danger,
    },
    button_row: {
        flexDirection: 'row',
        gap: 24,
        marginBottom: 28,
    },
    circleButton: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: Colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.primary,
        shadowOpacity: 0.35,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 5 },
        elevation: 5,
    },
    resetButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 999,
        backgroundColor: Colors.white,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    resetText: {
        color: Colors.slate,
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 1,
    },
})
