import { StyleSheet } from "react-native";

export const CountStyle = StyleSheet.create({
    container: {
        flex: 1,
        padding: 20,
        justifyContent: 'center',
        backgroundColor: '#f2f6fc',
    },
    TouchableOpacity: {
        borderRadius: 12,
        backgroundColor: '#1e3a5f',
        paddingVertical: 16,
        margin: 6,
        alignItems: 'center',
        shadowColor: '#1e3a5f',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    TouchableOpacityText: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: 'bold',
    },
    TouchableOpacityReset: {
        borderRadius: 12,
        backgroundColor: '#ef4444',
        paddingVertical: 16,
        margin: 6,
        marginTop: 20,
        alignItems: 'center',
        shadowColor: '#ef4444',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    TextCountResult: {
        fontSize: 44,
        fontWeight: 'bold',
        color: '#1e3a5f',
        textAlign: 'center',
        alignSelf: 'stretch',
        margin: 20,
        paddingVertical: 30,
        backgroundColor: '#ffffff',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
})
