import { StyleSheet } from "react-native";

export const CountStyle = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f9ff',
    },
    card: {
        alignSelf: 'stretch',
        alignItems: 'center',
        paddingVertical: 44,
        marginBottom: 36,
        backgroundColor: '#ffffff',
        borderRadius: 28,
        shadowColor: '#0ea5e9',
        shadowOpacity: 0.15,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    cardLabel: {
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 3,
        color: '#7ca6c0',
        marginBottom: 6,
    },
    cardValue: {
        fontSize: 72,
        fontWeight: '800',
        color: '#0c4a6e',
    },
    cardValueNegative: {
        color: '#ef4444',
    },
    button_row: {
        flexDirection: 'row',
        gap: 24,
        marginBottom: 28,
    },
    circleButton: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: '#0ea5e9',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#0ea5e9',
        shadowOpacity: 0.35,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 5 },
        elevation: 5,
    },
    resetButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 12,
        paddingHorizontal: 28,
        borderRadius: 999,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#bae6fd',
    },
    resetText: {
        color: '#4a7a9b',
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 1,
    },
})
