import { StyleSheet } from 'react-native';
import { Colors } from './colors';
export const FormStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 10,
        backgroundColor: Colors.background,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 12,
    },
    summaryBox: {
        borderRadius: 16,
        padding: 12,
        marginBottom: 8,
        backgroundColor: Colors.navy,
        shadowColor: Colors.navy,
        shadowOpacity: 0.35,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
    },
    summaryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 5,
    },
    summaryTitle: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 2,
        color: Colors.lightBlue,
    },
    summaryRow: {
        flexDirection: 'row',
        marginBottom: 3,
    },
    summaryKey: {
        width: 78,
        fontSize: 13,
        fontWeight: '600',
        color: Colors.lightBlue,
    },
    summaryValue: {
        flex: 1,
        fontSize: 13,
        color: Colors.white,
    },
    section: {
        marginVertical: 4,
        backgroundColor: Colors.white,
        borderRadius: 14,
        padding: 10,
        shadowColor: Colors.dark,
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 2,
    },
    labelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 6,
    },
    label: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
        color: Colors.primary,
    },
    radioText: {
        fontSize: 15,
        color: Colors.textDark,
    },
    dropdownPlaceholder: {
        fontSize: 15,
        color: Colors.muted,
    },
    dropdownSelected: {
        fontSize: 15,
        color: Colors.dark,
    },
    TextInput: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 10,
        paddingVertical: 9,
        paddingHorizontal: 12,
        fontSize: 15,
        color: Colors.dark,
        backgroundColor: Colors.inputBg,
    },
    commentInput: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 10,
        paddingVertical: 9,
        paddingHorizontal: 12,
        fontSize: 15,
        color: Colors.dark,
        height: 54,
        textAlignVertical: 'top',
        backgroundColor: Colors.inputBg,
    },
    radio_pack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    radioItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 20,
    },
    Dropdown: {
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 10,
        paddingVertical: 9,
        paddingHorizontal: 12,
        backgroundColor: Colors.inputBg,
    },
    button_row: {
        flexDirection: 'row',
        gap: 10,
        paddingTop: 10,
        paddingBottom: 4,
    },
    clearButton: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 6,
        backgroundColor: Colors.white,
        borderWidth: 1,
        borderColor: Colors.border,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
    },
    clearButtonText: {
        color: Colors.slate,
        fontSize: 16,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    switchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 4,
        backgroundColor: Colors.white,
        borderRadius: 14,
        paddingVertical: 6,
        paddingHorizontal: 12,
        shadowColor: Colors.dark,
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 2,
    },
});
