import { StyleSheet } from 'react-native';
export const FormStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 10,
        backgroundColor: '#f2f6fc',
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 24,
    },
    summaryBox: {
        borderRadius: 12,
        padding: 12,
        margin: 5,
        marginBottom: 10,
        backgroundColor: '#1e3a5f',
        maxHeight: 130,
        shadowColor: '#1e3a5f',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    summaryText: {
        fontSize: 15,
        marginBottom: 2,
        color: '#ffffff',
    },
    section: {
        marginHorizontal: 5,
        marginVertical: 4,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 10,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    label: {
        fontSize: 15,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#1e3a5f',
    },
    TextInput: {
        borderWidth: 1,
        borderColor: '#c5d3e8',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        fontSize: 15,
        backgroundColor: '#f8fafd',
    },
    commentInput: {
        borderWidth: 1,
        borderColor: '#c5d3e8',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        fontSize: 15,
        height: 70,
        textAlignVertical: 'top',
        backgroundColor: '#f8fafd',
    },
    radio_pack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    radioItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 18,
    },
    Dropdown: {
        borderWidth: 1,
        borderColor: '#c5d3e8',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: '#f8fafd',
    },
    switchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginHorizontal: 5,
        marginVertical: 4,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        paddingVertical: 8,
        paddingHorizontal: 12,
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
});
